### ISSUE TITLE
Dataset consistency

### ISSUE THREAD

**Issue by ymahlich** [PNNL-CompBio/coderdata#229] opened 2024-10-11 19:01 UTC
Downloading the data from figshare I realized that some of the dataset files are tab separated, some comma separated, some compressed, some uncompressed.

Is there a specific reason for that? I understand that everything is handled internally so as long as I am directly interacting with the data through coderdata objects, it might not be important but maybe we want to be consistent about this?

As far as I can tell, currently the "schema" behind what datatype is which format is as follows:

| data type | csv | csv.gz | tsv.gz |
|:--------:|:--------:|:--------:|:--------:|
| copy_number |  | x |   |
| drug_descriptor |   |  | x |
| drugs |  |  | x |
| experiments |  |  | x |
| mutations |  | x |  |
| proteomics |  | x |  |
| samples | x |  |  |
| transcriptomics |  | x |  |

**Comment by sgosline** [comment] 2024-10-11 19:59
Yes! First off, pandas can read in whatever so it doesn't matter. I default to csv unless it has drug information, which requires tabs (because drug descriptors and names have commas and quotes in them). we could probably gzip the samples files for consistency.

**Comment by jjacobson95** [comment] 2024-10-14 16:15
I like that we can preview the samples files on figshare when not gzipped, but I don't have a strong opinion either way. 

This could very easily be modified in lines 321,323 of [build_all.py](https://github.com/PNNL-CompBio/coderdata/blob/main/build/build_all.py#L321) during the validation step.

**Comment by sgosline** [comment] 2024-11-12 01:07
Duplicate of #246.

**Closed by sgosline** 2024-11-12 01:07 UTC
Labels: 'build' update
